### ISSUE TITLE
Android Auth Issues

### ISSUE THREAD

**Issue by ddutchie** [Elringus/UnityGoogleDrive#34] opened 2018-12-24 07:21 UTC
On Android I am not getting an auth screen. 

It works fine on iOS. Below is error log. 
No idea when this issue crept in. I found that play service resolver was not correctly downloading dependencies, but I fixed that.

`12-24 09:13:19.233 24816 24836 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x0
12-24 09:13:19.522 24816 24836 E Unity   : AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='SetResponseListener' signature='(Lcom.elringus.unitygoogledriveandroid.AuthorizationActivity$OnAuthorizationResponseListener;)V' in class Lcom.elringus.unitygoogledriveandroid.AuthorizationActivity;
12-24 09:13:19.522 24816 24836 E Unity   : java.lang.NoSuchMethodError: no static method with name='SetResponseListener' signature='(Lcom.elringus.unitygoogledriveandroid.AuthorizationActivity$OnAuthorizationResponseListener;)V' in class Lcom.elringus.unitygoogledriveandroid.AuthorizationActivity;
12-24 09:13:19.522 24816 24836 E Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:49)
12-24 09:13:19.522 24816 24836 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
12-24 09:13:19.522 24816 24836 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
12-24 09:13:19.522 24816 24836 E Unity   : 	at com.unity3d.player.UnityPlayer$c$1.handleMessage(Unknown Source:151)
12-24 09:13:19.522 24816 24836 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:104)
12-24 09:13:19.522 24816 24836 E Unity   : 	at android.os.Looper.loop(Looper.java:166)
12-24 09:13:19.522 24816 24836 E Unity   : 	at com.unity3d.player.UnityPlayer$c.run(Unknown Source:20)
12-24 09:13:19.522 24816 24836 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jcla
12-24 09:13:20.528 24816 24874 E Unity   : java.io.EOFException
12-24 09:13:20.528 24816 24874 E Unity   :  
12-24 09:13:20.528 24816 24874 E Unity   : (Filename:  Line: 390)
12-24 09:13:20.528 24816 24874 E Unity   : 
12-24 09:13:20.773 24816 24868 E Unity   : java.io.EOFException
12-24 09:13:20.773 24816 24868 E Unity   :  
12-24 09:13:20.773 24816 24868 E Unity   : (Filename:  Line: 390)
12-24 09:13:20.773 24816 24868 E Unity   : 
12-24 09:13:59.802 24816 24836 I Unity   : Rebuilt
12-24 09:13:59.802 24816 24836 I Unity   :  `

**Comment by Elringus** [comment] 2018-12-24 10:35
Looks like it can't find `SetResponseListener` method to post the callback. Given you didn't change anything in the project, it's most likely due to changes in android native libraries or some related Unity's stuff. I will try to reproduce this on my test device and get back with the results.

**Comment by Elringus** [comment] 2018-12-24 12:11
Tried testing with Unity 2018.3.0f2 and had some issues initially; most likely due to an outdated appauth dependency. I've [updated the version](https://github.com/Elringus/UnityGoogleDrive/commit/5c83c05b53ea5696f28e1b004a8be1d02cdd23ea#diff-e4b8417ae363f6598e17ea89cce0a3e3R3), deleted the plugins directory, updated google play resolver package and re-resolved the android plugins. After that everything worked fine. Here are the android build settings I've used:

![](https://i.gyazo.com/2f49599d32473207b68890b7ba3ba4b0.png)

Please let me know whether the above steps and build settings resolve the issue for you. Don't forget to update the required appauth version in the [Dependencies.xml](https://github.com/Elringus/UnityGoogleDrive/blob/master/Assets/UnityGoogleDrive/Editor/Dependencies.xml#L3) before resolving the android plugins.

**Comment by TwerkyMan** [comment] 2018-12-27 15:39
Hello! I downloaded the newer version and got a few errors. First of all I got this:

Assets/UnityGoogleDrive-master 1/UnityGoogleDrive-master/Assets/ThirdParty/UnityCommon/Runtime/Utilities/StringUtils.cs(49,24): error CS0117: `string' does not contain a definition for `IsNullOrWhiteSpace'

I replaced "IsNullOrWhiteSpace" with "IsNullOrEmpty" and it got away. Then I got an error which basically said that "ProjectFileHook" needs .NET 4.0 to work. I'm using .NET 3.5 Equivalent and the complatibility level is .NET 2.0. The matter of fact is I cannot change my .NET 3.5 to 4.0 because I use many other plugins which require .NET 3.5 or 2.0. Thanks for any help!

**Comment by TwerkyMan** [comment] 2018-12-27 15:42
Here's the second error:

Assets/UnityGoogleDrive-master 1/UnityGoogleDrive-master/Assets/Editor/ProjectFileHook.cs(18,43): error CS1644: Feature `expression bodied members' cannot be used because it is not part of the C# 4.0 language specification

**Comment by Elringus** [comment] 2018-12-27 17:48
The project (not the package) requires .NET 4.x and Unity 2018.3. If you're adding the plugin to an existing project, you don't need to copy the whole project; all the plugin files are located in `Assets/UnityGoogleDrive` folder, other stuff is just for testing purposes.

**Comment by TwerkyMan** [comment] 2018-12-28 12:09
Well, I got rid of all the errors and built my application to my mobile device. I hate to say this, but the issue still occurs to me.

**Comment by Elringus** [comment] 2018-12-28 12:36
That's sad. Looks like we're on the square one then, as I still can't reproduce this. Guess we'll need a repro case in a clean project to move forward.

**Comment by TwerkyMan** [comment] 2018-12-31 16:01
Come to think of it, couldn't this error be caused by our project names having uppercase letters in it? I remember doing a workaround about this(it required to change the file in Plugins folder), but as I can see the plugin folder has been deleted in the latest update. Let me know what you think of this.

**Comment by Elringus** [comment] 2018-12-31 16:49
It was package name actually, not project name. The requirement stays the same atm, and the workaround should be working. Plugins folder contains native libs for the target platform (android/ios). They're downloaded automatically when resolving the dependencies with google play resolver; the libs were never included with the package before.

**Comment by TwerkyMan** [comment] 2019-01-05 14:32
I figured it out!!! I checked the AndroidManifest in the Plugins forlder and found that I didn't use the workaround after the update. I inserted my application Id (lowercased) and it worked! Please the others know about the workaround, so they won't have to struggle with this as I did. Take care!

**Comment by Elringus** [comment] 2019-01-05 14:39
Glad you've finally made it working! The workaround is actually [specified](https://github.com/Elringus/UnityGoogleDrive#my-application-id-andriodios-is-mixed-cased-and-i-cant-change-it) in the FAQ section of the readme and also mentioned in the setup section.

**Closed** 2019-01-16 15:43 UTC
Labels: help wanted, need reproduction
