### ISSUE TITLE
Straight scene test for iOS?

### ISSUE THREAD

**Issue by samavan** [Elringus/UnityGoogleDrive#25] opened 2018-09-02 15:02 UTC
Hi!

Set the settings file as mentioned, edited the bundleId then run a direct build to iOS.

First build gave this : 

![image from ios](https://user-images.githubusercontent.com/6184992/44957346-43659800-af0c-11e8-8c91-ed3819fe3410.png)

Then edited WindowRect variable from the first scene (which do not even match on mac book display...)
Made another Build & Replace then getting new error : 
<img width="732" alt="screen shot 2018-09-02 at 23 53 56" src="https://user-images.githubusercontent.com/6184992/44957359-6d1ebf00-af0c-11e8-81b6-e49f157e2a4e.png">

... which now always show up even with a Build & Replace to get a fresh project from scratch...

Any idea? ...
That would be super kind!! ^_^
Thank you so much :)

**Comment by Elringus** [comment] 2018-09-02 15:12
Hi, The scenes you are trying to run (and the project itself) are for internal testing only. I recommend importing a package from the releases page instead.

**Comment by samavan** [comment] 2018-09-02 15:29
I see... 
Did imported the package first but there were no demo scene at all then...  
A bit unfortunate.. :(

**Comment by samavan** [comment] 2018-09-02 15:35
If you could prepare a sample scene I would make a cool interface using Unity UI to be sure your demo-scene fit every screen ratio! 
That would make your plugin a bit more friendly use for user like me at least! :) 
What do you think? ^_^.

I also tried this plugin : https://github.com/midworld/unity-googledrive
That was super easy to test it out with the single demo scene.
Works a charm from Editor and StandAlone. 
Unfortunately the iOS sign in is a bit out of dated... I am stuck.

A simple demo scene to Login > Upload file > download file.
I can assist you with the unity UI if you need :) !

**Comment by Elringus** [comment] 2018-09-02 15:41
Well, the pull requests are open, so you're welcome to contribute :) You can use the test scripts inside /Assets/Scripts for reference implementation or make your own. I should warn you though, that there are some issues with auth on iOS (#24), so this solution might also not work there at the moment.

**Comment by samavan** [comment] 2018-09-02 15:43
Google drive doesn't support OAuth2 anymore from Smartphones (iOS & android)...
Do you also use this?
Or the new requirement?... 
Just to know before I dig in :D ...

**Comment by Elringus** [comment] 2018-09-02 15:49
Well, I've never heard that Google dropped support for OAuth on mobiles. Official docs are stating that it's supported: https://developers.google.com/identity/protocols/OAuth2InstalledApp And it's actually working (tested just a couple days before). The issue is with getting the auth response while the app is not in focus; you can find the details in #21 and #24.

**Comment by samavan** [comment] 2018-09-02 15:55
I see... 
Well it mentions  "OAuth request  to Google in embedded  browsers known as 'Web-views'".
the article is from August 2016...

![s__12361732](https://user-images.githubusercontent.com/6184992/44957949-e5d54980-af13-11e8-9954-e43aa9c35126.jpg)

**Comment by Elringus** [comment] 2018-09-02 16:02
It's about embedded browsers, right. But I'm using a standalone browser, so it doesn't matter. The issue is that when a standalone browser opens, the app itself halts (it's not allowed to run in background on mobiles) and issues with serving the incoming loopback request appear. Unfortunately, I currently don't have enough time to properly test it on ios and android devices and fix the issue.

**Comment by Elringus** [comment] 2018-09-09 14:04
I've published a [new release](https://github.com/Elringus/UnityGoogleDrive/releases/tag/v0.20-alpha) with the reworked test and example scripts. The UI will now adapt to the screen resolution and remain usable on any device. The Android and iOS authentication are also fixed in this release.

**Closed by Elringus** 2018-09-09 14:04 UTC
Labels: enhancement
