### ISSUE TITLE
Android redirection issues

### ISSUE THREAD

**Issue by BioBazard** [Elringus/UnityGoogleDrive#33] opened 2018-11-16 10:51 UTC
Hello,
First I want to say again thank you for this plugin.
As said in the title I have a issues with the redirection. After the authentification it don't go back to the app.

I followed the tutorial instruction and I have create 2 OAuth client ID (a web app and iOS).
But when I authenticate it seems use the web app OAuth (because the name that appears is the name of the web app). Is this normal ?

What should I do for after an authentication go back to the app?
[Here is a screen of the google drive settings if it can help.](https://i.imgur.com/Zt1BPXi.png)

Thanks.

**Comment by Elringus** [comment] 2018-11-16 12:33
Make sure your app id is all lower cased. If it won't help, use adb utility to extract the system log at the moment when redirect occurs to find out, what's causing the issue.

**Comment by BioBazard** [comment] 2018-11-16 14:04
I have try with the bundle id in lower case but I have still the issues ...
[This is the catched error](https://i.imgur.com/30eys0N.png)
Does that tell you anything?

**Comment by Elringus** [comment] 2018-11-16 14:55
Not really. There should be calls to either UnityPlayer or unitygoogledriveandroid/AuthorizationActivity.

**Comment by Elringus** [comment] 2018-11-16 16:20
I've just tested android build with Unity 2018.3b10 and it worked fine. It could be the issue is with your project config or 3rd party packages. Try re-tracing all the setup steps and building the github example project.

**Comment by TwerkyMan** [comment] 2018-11-19 16:29
I seem to get some redirection issues too. When signing in it takes me to google.com and not my app (like it used to do before). The only thing I did was downgrade my Unity from 2019 alpha to 2018.2.16f1 (due to weird errors). Thanks for any help in advance.

**Comment by pavelb7812** [comment] 2018-11-21 15:30
Join to this issue. Its working in Editor and iOS but not on Android.

After choosing account for Google Drive its not redirect to my response page with "Please, return to the app" text for some reason. Instead of this it waiting 10-20 seconds and redirect to google.com. File not uploading on Android.

Thank you for any help.

**Comment by Elringus** [comment] 2018-11-21 20:55
Thanks for the reports guys! Unfortunately, I don't have time to fix this right now, so in case anyone have experience with native android stuff, check out the library used for the auth activity on android: https://github.com/Elringus/UnityGoogleDriveAndroid/blob/master/library/src/main/java/com/elringus/unitygoogledriveandroid/AuthorizationActivity.java Most likely the source of the issue is there.

**Comment by Elringus** [comment] 2018-11-30 15:34
I've tried to reproduce this issue again on a new clean project using another google drive account, but it still worked fine and redirected me back to the app. In case anyone has an idea how to reproduce it, please let me know, otherwise I can't really help in any way.

**Comment by TwerkyMan** [comment] 2018-12-01 15:50
Well, I'm using Unity 2018.2.16f1 and this occurs so you can try to test it on this version. Also, maybe there are some Unity settings (for example Run In Background), which can lead to this happening?

**Comment by Elringus** [comment] 2018-12-01 15:57
I've tested it on both Unity 2018.2 and 2018.3 beta. `Run In Background` has no effect on mobiles, as far as I know, but will check it anyway.

**Comment by Elringus** [comment] 2018-12-24 15:10
Hey guys, I've tested android again and was able to find some issues possibly related to an outdated appauth lib. Please try to follow the steps as stated here: https://github.com/Elringus/UnityGoogleDrive/issues/34#issuecomment-449726652 and let me know whether it resolved the redirection issue.

**Comment by Elringus** [comment] 2019-04-24 17:03
Closing this for now. In case anyone will be able to make a stable repro case, feel free to re-open this issue.

**Closed by Elringus** 2019-04-24 17:03 UTC
Labels: help wanted, need reproduction
